### ISSUE TITLE
error ( just added my virtual env folder to project directory)

### ISSUE THREAD

**Issue by tejesh95** [heroku/heroku-django-template#6]
![screenshot from 2014-11-25 09 15 26](https://cloud.githubusercontent.com/assets/6937958/5177704/a5d98e28-7483-11e4-9739-bc22d84d7554.png)

This error pops up while running my server manage.py

bash -cl "/home/tejesh/PycharmProjects/heroku-django-template/django_heroku_env/bin/python /home/tejesh/Apps/pycharm-3.4.1/helpers/pycharm/django_manage.py runserver /home/tejesh/PycharmProjects/heroku-django-template"
Traceback (most recent call last):
  File "/home/tejesh/Apps/pycharm-3.4.1/helpers/pycharm/django_manage.py", line 23, in <module>
    run_module(manage_file, None, '__main__', True)
  File "/usr/lib/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tejesh/PycharmProjects/heroku-django-template/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/tejesh/PycharmProjects/heroku-django-template/django_heroku_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/tejesh/PycharmProjects/heroku-django-template/django_heroku_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/tejesh/PycharmProjects/heroku-django-template/django_heroku_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/tejesh/PycharmProjects/heroku-django-template/django_heroku_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/tejesh/PycharmProjects/heroku-django-template/django_heroku_env/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 14, in <module>
    from django.db.migrations.executor import MigrationExecutor
  File "/home/tejesh/PycharmProjects/heroku-django-template/django_heroku_env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 5, in <module>
    from .loader import MigrationLoader
  File "/home/tejesh/PycharmProjects/heroku-django-template/django_heroku_env/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 8, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "/home/tejesh/PycharmProjects/heroku-django-template/django_heroku_env/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 9, in <module>
    class MigrationRecorder(object):
  File "/home/tejesh/PycharmProjects/heroku-django-template/django_heroku_env/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 23, in MigrationRecorder
    class Migration(models.Model):
  File "/home/tejesh/PycharmProjects/heroku-django-template/django_heroku_env/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 24, in Migration
    app = models.CharField(max_length=255)
  File "/home/tejesh/PycharmProjects/heroku-django-template/django_heroku_env/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 1012, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "/home/tejesh/PycharmProjects/heroku-django-template/django_heroku_env/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 146, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/home/tejesh/PycharmProjects/heroku-django-template/django_heroku_env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/home/tejesh/PycharmProjects/heroku-django-template/django_heroku_env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 40, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

Process finished with exit code 1

------------------------------------------------------------------------------------------------------------------------
THE BELOW ERROR SHOWS UP WHEN RUNNING 

tejesh@tejesh-K53SM ~/PycharmProjects/heroku-django-template $ heroku run python manage.py syncdb
Running `python manage.py syncdb` attached to terminal... up, run.9438
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 98, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings '{{ project_name }}.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named {{ project_name }}.settings

Note: I use pycharm IDE

**Comment by pydanny** [comment]
In the friendliest way possible, here is my advice: Don't add envs to your project repo.

If you take it out of your project both Heroku and PyCharm should work better.
