### ISSUE TITLE
Problem with collectstatic with djangorestframework==3.6.0 or 3.6.1 and whitenoise==3.2 or 3.3

### ISSUE THREAD

**Issue by neosergio** [heroku/heroku-django-template#62]
When I tried to deploy in heroku a project with djangorestframework>=3.6.0 I got this error
`
-----> Python app detected
-----> Installing requirements with pip
       Collecting djangorestframework==3.6.0 (from -r /tmp/build_7659bf556ac45b456a1b91407a022c10/projectname-e014b5a/requirements/base.txt (line 5))
         Downloading djangorestframework-3.6.0-py2.py3-none-any.whl (1.2MB)
       Installing collected packages: djangorestframework
         Found existing installation: djangorestframework 3.5.3
           Uninstalling djangorestframework-3.5.3:
             Successfully uninstalled djangorestframework-3.5.3
       Successfully installed djangorestframework-3.6.0
     $ python manage.py collectstatic --noinput
       Post-processing 'rest_framework/docs/css/bootstrap-theme.min.css' failed!
       Traceback (most recent call last):
         File "manage.py", line 22, in <module>
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
           self.execute(*args, **cmd_options)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
           output = self.handle(*args, **options)
         File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 193, in handle
           collected = self.collect()
         File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 145, in collect
           raise processed
       whitenoise.storage.MissingFileError: The file 'rest_framework/docs/css/../fonts/glyphicons-halflings-regular.eot' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7f8e7dffd750>.
       The CSS file 'rest_framework/docs/css/bootstrap-theme.min.css' references a file which could not be found:
         rest_framework/docs/css/../fonts/glyphicons-halflings-regular.eot
       Please check the URL references in this CSS file, particularly any
       relative paths which might be pointing to the wrong location.
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed
`

I think problem could be related to glyphicons but I'm not sure. I was able to deploy successfully with djangorestframework==3.5.4 (or lower) and whitenoise (3.2 or 3.3)

**Comment by neosergio** [comment]
This seems to be a djangorestframework issue, see this issue for further reference https://github.com/encode/django-rest-framework/issues/4950

**Comment by neosergio** [comment]
This issue is solved in djangorestframework==3.6.2
